apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: pomelo
spec:
  ports:
  - port: 3010
    targetPort: 3010
    name: connector
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: pomelo
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: felipejfc/nginx-ws-lb:0.0.2
          ports:
            - containerPort: 3010
          env:
            - name: LISTEN_PORT
              value: "3010"
            - name: SERVICE_DOMAIN
              value: "pomelotest.felipejfc.com"
            - name: K8S_SERVICE
              value: "pomelo-connector.pomelo.svc.cluster.local"
            - name: FORWARD_PORT
              value: "3010"
            - name: K8S_DNS_SERVER
              value: "10.0.0.10"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
