apiVersion: v1
kind: ReplicationController
metadata:
  name: pomelo-connector-server
  namespace: pomelo
spec:
  replicas: 2
  selector:
    app: pomelo-connector-server
  template:
    metadata:
      labels:
        app: pomelo-connector-server
    spec:
      containers:
      - name: pomelo-connector-server
        image: felipejfc/pomelo-on-k8s:0.0.3
        ports:
          - containerPort: 3010
        env:
          - name: REDIS_HOST
            value: redis-service.default
          - name: REDIS_PORT
            value: "6379"
