apiVersion: v1
kind: Service
metadata:
  name: pomelo-gate
  labels:
    app: pomelo-gate
  namespace: pomelo
spec:
  ports:
  - port: 3010
    targetPort: 3010
    name: gate
  selector:
    app: pomelo-gate
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pomelo-gate
  namespace: pomelo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pomelo-gate
    spec:
      containers:
      - name: pomelo-gate
        image: felipejfc/pomelo-on-k8s:0.0.4
        ports:
          - containerPort: 3010
            name: gate
        env:
          - name: REDIS_HOST
            value: redis.default
          - name: REDIS_PORT
            value: "6379"
          - name: SERVICE_DOMAIN
            value: pomelotest.felipejfc.com
          - name: SERVER_TYPE
            value: gate
